trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

variables:
  azureSubscription: '70b03d67-56bd-4483-8274-f4966fb4bdc5'
  appName: 'example-app-service-mo'
  resourceGroup: 'rg-example'
  location: 'West Europe'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '14.x'
    checkLatest: true

- script: |
    npm install
    npm test
  displayName: 'Install and test the application'

- task: AzureCLI@2
  inputs:
    azureSubscription: $(70b03d67-56bd-4483-8274-f4966fb4bdc5)
    scriptType: bash
    scriptLocation: inlineScript
    inlineScript: |
      az webapp up --name $(example-app-service-mo) --resource-group $(rg-example) --location $(West Europe)
  displayName: 'Deploy to Azure Web App'


