trigger:
  branches:
    include:
      - main  # Trigger pipeline on commits to the 'main' branch

pool:
  vmImage: 'ubuntu-latest'  # Specify the VM image for the pipeline (Ubuntu)

steps:
- task: UseNode@2  # Install Node.js
  inputs:
    versionSpec: '14.x'  # Set Node.js version (change as needed)

- script: |
    npm install  # Install dependencies
    npm test     # Run tests (optional, remove if you don't have tests yet)
  displayName: 'Install dependencies and run tests'

- task: AzureWebApp@1  # Deploy to Azure App Service
  inputs:
    azureSubscription: 'YOUR_AZURE_SUBSCRIPTION'  # Replace with your actual Azure Subscription name
    appName: 'mht-example-app-service'  # Replace with your Azure App Service name
    package: '$(System.DefaultWorkingDirectory)/$(Build.DefinitionName)/**/*.zip'  # Path to your build artifact
    deploymentMethod: 'auto'  # Auto deploy (can be customized)

